export const INVALID_CREDENTIALS = 'INVALID_CREDENTIALS';
export const INCOMPLETE_FIELD = 'INCOMPLETE_FIELD';
export const NOT_AUTHORIZED = 'NOT_AUTHORIZED';
export const DUPLICATED_USER = 'DUPLICATED_USER';