module.exports = {
    INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
    INCOMPLETE_FIELD: 'INCOMPLETE_FIELD',
    NOT_AUTHORIZED: 'NOT_AUTHORIZED',
    DUPLICATED_USER: 'DUPLICATED_USER',
    MISSING_PARAM: 'MISSING_PARAM',
    INVALID_PARAM: 'INVALID_PARAM'
};